#pragma config(Sensor, dgtl1,  StartButton,         sensorTouch)
#pragma config(Motor,  port1,           Motor1,        tmotorNormal, openLoop)
#pragma config(Motor,  port10,          Motor10,       tmotorNormal, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main()
{
  untilBump(StartButton);

  {
    startMotor(Motor1, 127);                  //Motors will start
    startMotor(Motor10, 127);
    wait(5);                                // Motors will run for 5 seconds
    stopMotor(Motor1);                           // Motors will stop
    stopMotor(Motor10);
  }
}
